# Generated by Django 4.2.6 on 2023-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_user', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password123', max_length=30),
        ),
    ]
