# Generated by Django 4.2.6 on 2023-11-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_user', '0003_user_email_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NewUser',
        ),
    ]
